class Tip{
    constructor(){
        this.show();
    }
    display(){
        background(background10);
        this.show();
        tipsprev.mousePressed (()=>{
            this.hide();
            viewReport.display();
        })
    }
    show(){
        tipsEFullForm.show();
        tipsAFullForm.show();
        tipsRFullForm.show();
        tipsNFullForm.show();
        tipsprev.show();
        tipsEarn.show();
        tipsExercise.show();
        tipsExercise2.show();
        tipsAttitude.show();
        tipsRest.show();
        tipsNutrition.show();
    }
    hide(){
        tipsEFullForm.hide();
        tipsAFullForm.hide();
        tipsRFullForm.hide();
        tipsNFullForm.hide();
        tipsprev.hide();
        tipsEarn.hide();
        tipsExercise.hide();
        tipsExercise2.hide();
        tipsAttitude.hide();
        tipsRest.hide();
        tipsNutrition.hide();
    }
}